# Generated by Django 2.1.7 on 2019-03-27 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('hotel_date_in', models.DateField()),
                ('hotel_date_out', models.DateField()),
                ('no_of_nights', models.IntegerField()),
                ('safari_code', models.IntegerField()),
                ('safari_location', models.CharField(blank=True, max_length=200)),
                ('safari_start', models.DateField()),
                ('safari_end', models.DateField()),
                ('safari_days', models.IntegerField()),
                ('booking_number', models.IntegerField(blank=True)),
                ('booking_status', models.CharField(max_length=200)),
                ('invoice_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('paid_notpaid', models.CharField(max_length=200)),
                ('tour_leader', models.CharField(max_length=200)),
                ('week', models.IntegerField(blank=True)),
                ('no_of_adults', models.IntegerField()),
                ('no_of_children', models.IntegerField(blank=True)),
                ('arrival_flight', models.CharField(max_length=200)),
                ('room_type', models.CharField(max_length=200)),
                ('agent', models.CharField(max_length=200)),
                ('sxs_consultant', models.CharField(max_length=200)),
                ('depart_flight_number', models.CharField(max_length=200)),
                ('depart_flight_time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('file_handler', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comments', models.CharField(max_length=200)),
                ('car_no', models.CharField(blank=True, max_length=200)),
                ('driver', models.CharField(max_length=200)),
                ('start_endpoint', models.CharField(max_length=200)),
            ],
        ),
    ]
