# Generated by Django 2.1.7 on 2019-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190402_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackers',
            name='safari_comments',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
