# Generated by Django 2.1.7 on 2019-04-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_trackers_safari_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackers',
            name='safari_comments',
        ),
    ]
